"""empty message

Revision ID: db901f56d6dc
Revises: 09aa4608a1b9
Create Date: 2025-08-10 11:30:10.028350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db901f56d6dc'
down_revision: Union[str, Sequence[str], None] = '09aa4608a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'UserProfile', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserProfile', type_='unique')
    # ### end Alembic commands ###
