"""Fix: make category.name NOT NULL

Revision ID: ff65219167d5
Revises: cf2e3e0b27f3
Create Date: 2025-08-13 21:59:48.156596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff65219167d5'
down_revision: Union[str, Sequence[str], None] = 'cf2e3e0b27f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Categories', type_='unique')
    # ### end Alembic commands ###
